import { Job } from '@/types'

export const mockJobs: Job[] = [
  {
    id: 'j1',
    sourceKey: 'wwr',
    title: 'Frontend Engineer – Next.js + React (Remote)',
    url: 'https://weworkremotely.com/',
    postedAt: '2025-12-23T02:10:00Z',
    category: 'Web/Frontend',
    skills: ['Next.js', 'React', 'TypeScript', 'Tailwind', 'API'],
    remote: true,
    applicantsMin: 10,
    applicantsMax: 15,
    ehrTwd: 1800,
    score: 82,
    reasonsTop: ['有效時薪高於同類別 p75', '技能命中：React/Next.js', '競爭低：已投稿約 13'],
    breakdown: { P: 0.82, Fit: 0.76, Q: 0.62, R: 0.20, Comp: 0.38 },
    reasonsPositive: ['有效時薪顯著高於同類別 p75', '技能命中率高（前端框架與 TS）', '案子描述含交付物與技術細節'],
    reasonsNegative: ['競爭中等（投稿區間 10–15）', '需求未明確列出驗收方式'],
    fxAsOf: '2025-12-23T00:00:00Z',
  },
  {
    id: 'j2',
    sourceKey: 'yourator',
    title: '網站前端工程師（接案/約聘）',
    url: 'https://www.yourator.co/jobs',
    postedAt: '2025-12-22T11:30:00Z',
    category: 'Web/Frontend',
    skills: ['React', 'Next.js', 'UI', 'Figma'],
    remote: false,
    ehrTwd: 1200,
    score: 71,
    reasonsTop: ['技能吻合：React/Next.js', '需求描述清楚', '競爭指標缺值（採保守）'],
    breakdown: { P: 0.63, Fit: 0.78, Q: 0.70, R: 0.18, Comp: 0.40 },
    reasonsPositive: ['技能匹配度高（React/Next.js）', '工作內容描述具體（頁面/元件）'],
    reasonsNegative: ['遠端限制（偏現場/混合）', '投稿人數未提供（使用預設競爭懲罰）'],
    fxAsOf: '2025-12-23T00:00:00Z',
  },
  {
    id: 'j3',
    sourceKey: 'wwr',
    title: 'Data / Scraping Contractor – ETL + APIs',
    url: 'https://weworkremotely.com/',
    postedAt: '2025-12-21T19:05:00Z',
    category: 'Data/Scraping',
    skills: ['Python', 'Scraping', 'ETL', 'PostgreSQL'],
    remote: true,
    applicantsMin: 25,
    applicantsMax: 50,
    ehrTwd: 2200,
    score: 69,
    reasonsTop: ['有效時薪高', '需求含技術細節', '競爭高（25–50）'],
    breakdown: { P: 0.90, Fit: 0.52, Q: 0.64, R: 0.28, Comp: 0.88 },
    reasonsPositive: ['有效時薪高於同類別 p75', '需求提及 ETL 與 DB'],
    reasonsNegative: ['競爭高（投稿區間 25–50）', '技能命中率中等（需 Python/ETL）'],
    fxAsOf: '2025-12-23T00:00:00Z',
  },
  {
    id: 'j4',
    sourceKey: 'yourator',
    title: '全端工程師（Next.js + Node.js）',
    url: 'https://www.yourator.co/jobs',
    postedAt: '2025-12-20T08:40:00Z',
    category: 'Web/Fullstack',
    skills: ['Next.js', 'Node.js', 'PostgreSQL', 'Auth'],
    remote: true,
    ehrTwd: 1450,
    score: 77,
    reasonsTop: ['技能命中：全端堆疊', '遠端', '競爭指標缺值（採保守）'],
    breakdown: { P: 0.72, Fit: 0.80, Q: 0.58, R: 0.22, Comp: 0.40 },
    reasonsPositive: ['技能命中率高（Next.js/Node/DB）', '可遠端'],
    reasonsNegative: ['需求未標示固定價/時薪（需再確認）', '投稿人數未提供（使用預設競爭懲罰）'],
    fxAsOf: '2025-12-23T00:00:00Z',
  },
  // 新增高風險案例
  {
    id: 'j5',
    sourceKey: 'wwr',
    title: 'Urgent simple project need immediately',
    url: 'https://weworkremotely.com/',
    postedAt: '2025-12-24T14:00:00Z',
    category: 'Web/Frontend',
    skills: ['JavaScript', 'HTML'],
    remote: true,
    applicantsMin: 60,
    applicantsMax: 80,
    ehrTwd: 400,
    score: 25,
    reasonsTop: ['競爭極高', '時薪過低', '需求模糊'],
    breakdown: { P: 0.15, Fit: 0.30, Q: 0.20, R: 0.80, Comp: 0.95 },
    reasonsPositive: ['可遠端工作'],
    reasonsNegative: ['競爭極高（60-80 申請者）', '時薪過低（TWD 400/hr）', '包含風險關鍵字：urgent, simple project'],
    fxAsOf: '2025-12-24T00:00:00Z',
  },
  {
    id: 'j6',
    sourceKey: 'yourator',
    title: 'Test project - no experience required, pay first',
    url: 'https://www.yourator.co/jobs',
    postedAt: '2025-12-24T15:00:00Z',
    category: 'Web/Frontend',
    skills: ['React'],
    remote: true,
    applicantsMin: 5,
    applicantsMax: 10,
    ehrTwd: 5000,
    score: 10,
    reasonsTop: ['詐騙信號', '可疑條件'],
    breakdown: { P: 0.95, Fit: 0.40, Q: 0.10, R: 0.95, Comp: 0.25 },
    reasonsPositive: ['時薪看似很高', '競爭不激烈'],
    reasonsNegative: ['包含詐騙關鍵字：test project, pay first, no experience required', '需求過於簡略'],
    fxAsOf: '2025-12-24T00:00:00Z',
  }
]